# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 1.12.2 ]
  pull_request:
    branches: [ 1.12.2 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: git
      run: |
        git config --global user.email "MA@email.com"
        git config --global user.name "MA"
        git submodule update --init --recursive
        
    - name: Build with Gradle
      run: ./gradlew
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PoreRT
        path: D:\a\
